#include <string>
#include <vector>

std::vector<std::string> fruits_list = {"Apple",
                                        "Banana",
                                        "Orange",
                                        "Mango",
  "Man",
                                        "Pineapple",
                                        "Strawberry",
                                        "Grape",
                                        "Watermelon",
                                        "Kiwi",
                                        "Pear",
                                        "Peach",
                                        "Plum",
                                        "Cherry",
                                        "Blueberry",
                                        "Raspberry",
                                        "Blackberry",
                                        "Lemon",
                                        "Lime",
                                        "Grapefruit",
                                        "Avocado",
                                        "Papaya",
                                        "Cantaloupe",
                                        "Honeydew",
                                        "Fig",
                                        "Pomegranate",
                                        "Cranberry",
                                        "Passionfruit",
                                        "Guava",
                                        "Lychee",
                                        "Dragonfruit",
                                        "Apricot",
                                        "Nectarine",
                                        "Tangerine",
                                        "Clementine",
                                        "Persimmon",
                                        "Gooseberry",
                                        "Kiwifruit",
                                        "Starfruit",
                                        "Plantain",
                                        "Date",
                                        "Jackfruit",
                                        "Elderberry",
                                        "Boysenberry",
                                        "Mulberry",
                                        "Olive",
                                        "Coconut",
                                        "Raspberry",
                                        "Blackcurrant",
                                        "Kumquat",
                                        "Loquat",
                                        "Tamarind",
                                        "Ugli fruit",
                                        "Breadfruit",
                                        "Ackee",
                                        "Physalis",
                                        "Durian",
                                        "Kiwano",
                                        "Pepino",
                                        "Rambutan",
                                        "Longan",
                                        "Lychee",
                                        "Mangosteen",
                                        "Pomelo",
                                        "Sapodilla",
                                        "Tamarillo",
                                        "Quince",
                                        "Persimmon",
                                        "Surinam cherry",
                                        "Miracle fruit",
                                        "Jabuticaba",
                                        "Tamarind",
                                        "Yuzu",
                                        "Acai berry",
                                        "Goji berry",
                                        "Barberry",
                                        "Bilberry",
                                        "Loganberry",
                                        "Marionberry",
                                        "Cloudberry",
                                        "Boysenberry",
                                        "Salak",
                                        "Horned melon",
                                        "Buddha's hand",
                                        "Finger lime",
                                        "Miracle berry",
                                        "Salak",
                                        "Carambola",
                                        "Feijoa",
                                        "Gac",
                                        "Imbe",
                                        "Monstera deliciosa",
                                        "Pepino",
                                        "Prickly pear",
                                        "Rollinia",
                                        "Safou",
                                        "Yangmei",
                                        "Chayote",
                                        "Kiwifruit",
                                        "Salak",
                                        "Carrot",
                                        "Potato",
                                        "Tomato",
                                        "Cucumber",
                                        "Lettuce",
                                        "Onion",
                                        "Garlic",
                                        "Bell pepper",
                                        "Spinach",
                                        "Broccoli",
                                        "Cauliflower",
                                        "Cabbage",
                                        "Celery",
                                        "Zucchini",
                                        "Eggplant",
                                        "Pumpkin",
                                        "Sweet potato",
                                        "Beetroot",
                                        "Radish",
                                        "Turnip",
                                        "Asparagus",
                                        "Artichoke",
                                        "Brussels sprouts",
                                        "Kale",
                                        "Swiss chard",
                                        "Bok choy",
                                        "Green bean",
                                        "Snow pea",
                                        "Pea",
                                        "Okra",
                                        "Corn",
                                        "Mushroom",
                                        "Avocado",
                                        "Rhubarb",
                                        "Fennel",
                                        "Leek",
                                        "Parsnip",
                                        "Rutabaga",
                                        "Watercress",
                                        "Arugula",
                                        "Collard greens",
                                        "Mustard greens",
                                        "Kohlrabi",
                                        "Endive",
                                        "Radicchio",
                                        "Escarole",
                                        "Turnip greens",
                                        "Dandelion greens",
                                        "Chicory",
                                        "Bamboo shoot",
                                        "Bean sprout",
                                        "Jicama",
                                        "Cassava",
                                        "Yam",
                                        "Tarot root",
                                        "Water chestnut",
                                        "Daikon",
                                        "Taro",
                                        "Yucca",
                                        "Chayote",
                                        "Horseradish",
                                        "Jerusalem artichoke",
                                        "Nopal",
                                        "Purslane",
                                        "Seaweed",
                                        "Hearts of palm",
                                        "Malanga",
                                        "Burdock root",
                                        "Lotus root",
                                        "Wasabi",
                                        "Lotus seed",
                                        "Samphire",
                                        "Celeriac",
                                        "Cardoon",
                                        "Sunchoke",
                                        "Arrowroot",
                                        "Celtuce",
                                        "Mache",
                                        "Radicchio",
                                        "Tatsoi",
                                        "Wakame",
                                        "Amaranth greens",
                                        "Broccoli rabe",
                                        "Chinese broccoli",
                                        "Fiddlehead ferns",
                                        "Ice plant",
                                        "Miner's lettuce",
                                        "Orache",
                                        "Purslane",
                                        "Red sorrel",
                                        "Sea kale",
                                        "Sea lettuce",
                                        "Salsify",
                                        "Skirret",
                                        "Winter purslane",
                                        "Bamboo shoot",
                                        "Sea grape",
                                        "Wapato",
                                        "Oca",
                                        "Celtuce"};
